### ISSUE TITLE
Example for http.server

### ISSUE THREAD

**Issue by lost-RD** [daurnimator/lua-http#37]
Can you please post one? I'm unsure how to use it and the docs are vague.

**Comment by daurnimator** [comment]
> unsure how to use it and the docs are vague.

That's mildly intentional: I have been modifying the api significantly and regularly.
I don't intend to document it until I've settled on a final API.

If you'd like, I can tell you how to use the current iteration (and/or you can help create the next iteration); but it will only be of short term value.

**Comment by lost-RD** [comment]
A solid starting point would be appreciated, yes. I'm happy to follow the changes after that.

**Comment by torhve** [comment]
There's a rudimentariy webserver in my IRC bot here: https://github.com/torhve/ivar2/blob/master/core/webserver.lua

**Comment by lost-RD** [comment]
@torhve, thanks for the reference. I'm attempting to compile the relevant code from your codebase into just a simple server that returns 404s but I haven't been able to get the server process to stay open yet though so I fear that your implementation may be beyond me.

I'm getting "unable to connect". I assume I've missed some necessary code.

[lua-http.zip](https://github.com/daurnimator/lua-http/files/351462/lua-http.zip)

**Comment by vavrusa** [comment]
I have some working code in here: https://github.com/CZ-NIC/knot-resolver/tree/master/modules/http

However, I had to fork a couple files - namely h2_connection, that creates new cqueue (so new pollfd per each connection) to use server pollfd instead, server to handle disconnects instead of throwing error and proper closing of streams to avoid leaking. I'm not sure what's @daurnimator plan for server, I could make PR for merging back to upstream if that's the way to go, but need to fixup tests first.

**Comment by daurnimator** [comment]
Sorry I haven't had a lot of time this week.

> However, I had to fork a couple files - namely h2_connection, that creates new cqueue (so new pollfd per each connection) to use server pollfd instead, server to handle disconnects instead of throwing error and proper closing of streams to avoid leaking.

Hmm, what were the issues here?

Re: http2 fd leaks, the cause of the leak has been fixed in cqueues upstream (just need a release).

**Comment by vavrusa** [comment]
I didn't have much time to work in it last weeks either, but I'll submit a PR when I get to it, it'd be more helpful probably. Some of those leaks are indeed fixed by the bugfixes with ephemeron tables in cqueues upstream.

The second thing is that h2_connection still creates pollfd for each connection, this is acceptable for clients but not great for server multiplexing multiple connections, because now it needs 2x number of open fds and extra overhead for creating them and overhead from nesting.

**Comment by daurnimator** [comment]
> The second thing is that h2_connection still creates pollfd for each connection, this is acceptable for clients but not great for server multiplexing multiple connections, because now it needs 2x number of open fds 

Compared to currently widely accepted http1 behaviour it should still be a significant reduction in fds.

But I'm curious how you'd propose to do this instead. Every other approach I came up with was racey.

> extra overhead for creating them and overhead from nesting.

Yeah I was concerned about this. It's part of the reason I haven't merged #21 

-------------------

If anyone would like to chat about the design of the http server API I'm happy to be contacted via IRC/xmpp/skype to discuss.

**Comment by vavrusa** [comment]
I propose to multiplex all client connections in parent cqueue. cqueue is just a wrapped kqueue/epollfd and while you can nest them, there is not much benefit in doing so (unless you want to i.e. serve only one socket from active socket at a time). I [changed the API](https://github.com/CZ-NIC/knot-resolver/blob/master/modules/http/http/h2_connection.lua#L94-L96) to either accept passed cqueue or reuse current cqueue.

**Comment by daurnimator** [comment]
@vavrusa, wouldn't they break [self-stepping](https://github.com/CZ-NIC/knot-resolver/blob/5a5d01d2b7bda426133fed67ffec0f82c76228fd/modules/http/http/h2_connection.lua#L400) if used from a thread managed by the same cqueue?

**Comment by daurnimator** [comment]
I made an example over here: https://gist.github.com/daurnimator/192dc5b210718dd129cfc1e5986df97b
I'm still not happy with the lua-http server API, so I'm not going to commit that example to the example directory.

Sadly I haven't found a way to write a useful server that doesn't use `pcall` (which means they can't work in an unmodified lua 5.1; though compat-5.3 does give a shim, it has global side-effects)

**Comment by lost-RD** [comment]
Thanks for this! So are you saying that I will need compat-5.3 to use this or should I instead be using a modified 5.1?

**Comment by daurnimator** [comment]
> Thanks for this! So are you saying that I will need compat-5.3 to use this or should I instead be using a modified 5.1?

I'm saying that in PUC lua 5.1 (luajit doesn't have this limitation) you **cannot** yield over a `pcall`. This makes it impossible to catch errors in a function that might yield.
Compat-5.3 replaces `pcall` with one that emulates it with coroutines. However loading that portion has global side effects, so I wouldn't want to use it in a library.
This fundamentally guides how the API for a server handing requests should look (if I want to support PUC lua 5.1): I guess the `pcall` call has to live *outside* of lua-http, so that people have the option to use compat-5.3.

**Comment by lost-RD** [comment]
Alright, I was planning to use LuaJIT anyway.

**Comment by lost-RD** [comment]
So I'm running the echo server with luajit and the loop is working. Problem is, I'm getting connection refused when I try to access the server in Chrome or with cURL.

**Comment by daurnimator** [comment]
The `get_split_as_sequence` method was removed a while ago.
I'm going to guess you have an old HEAD installed.

**Comment by lost-RD** [comment]
I did a fresh clone though, surely all files would be up to date? Or do I misunderstand git?

**Comment by daurnimator** [comment]
What do you guys think of this?
https://github.com/daurnimator/lua-http/blob/79093e32864ec28bb66af272e9ca02ede49ec466/examples/server_hello.lua

**Comment by lost-RD** [comment]
It's nice and readable. I can understand what it's doing. Only one question because I can't test it, will it send "Hello world!" in such a way that a web browser will interpret it as a web page? Or is that a further step?

**Comment by daurnimator** [comment]
Yes. However it is missing some features that you'd want in a internet facing server.
e.g. the example has no timeout passed to `get_headers`, which means that someone could send half a request and keep the tcp connection open to waste your server's resources.

**Comment by lost-RD** [comment]
I personally only want to use this as a server inside my home network that can receive requests and execute functions so that's fine by me.

On 4 Oct 2016, at 1:56 pm, "daurnimator" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. However it is missing some features that you'd want in a internet facing server.
e.g. the example has no timeout passed to get_headers, which means that someone could send half a request and keep the tcp connection open to waste your server's resources.

-

**Comment by daurnimator** [comment]
FYI the server-refactor branch was merged.
Any servers you've written will need to be modified for the new API.

**Comment by lost-RD** [comment]
[This is great!](http://i.imgur.com/iLQuK6H.png)

**Comment by daurnimator** [comment]
> This is great!

I wonder if you noticed it works for https on the same port? :)

**Comment by lost-RD** [comment]
> I wonder if you noticed it works for https on the same port? :)

Chrome warns me that the connection is "Not Secure". I guess I'll try Certbot, although it seems not to support Rasbian 8 OOTB.

**Comment by daurnimator** [comment]
> Chrome warns me that the connection is "Not Secure".

Yes it's self-signed. (and a new one every restart; http.server is a library, not a fully functional daemon!)


> I guess I'll try Certbot

It should be easy enough to use [lua-acme](https://www.zash.se/lua-acme.html) from inside of your application.

**Comment by lost-RD** [comment]
> It should be easy enough to use lua-acme from inside of your application.
Alright, I'll try that. Do you know of any examples of how to use lua-acme?

**Comment by daurnimator** [comment]
@zash ^^

**Comment by Zash** [comment]
I guess you'll need something like this:

```lua
local function https_request(url, post_body)
-- This is left as an exercise for daurnimator
end
local account = require"acme.account".new(privkey, directory_url, https_request);
```

And then look at the [example client implementation](https://code.zash.se/lua-acme/file/tip/luacme).

**Comment by daurnimator** [comment]
> local function https_request(url, post_body)
> -- This is left as an exercise for daurnimator
> end

See https://daurnimator.github.io/lua-http/#http.compat.socket

**Comment by Zash** [comment]
So this should work then:

```lua
local account = require"acme.account".new(privkey, directory_url, require"http.compat.socket".request);
```

And then have your HTTP server respond to `GET /.well-known/acme-challenge/:token` with `account.get_key_authz(token)` and you should be golden.
